### ISSUE TITLE
Base-url format

### ISSUE THREAD

**Issue by kvoer** [stichtingsem/ecosystem#1]
### How do we format the base-url?
The consequence of a unique base-url for each organisation (school) is that all endpoints (including web hooks and events) are specific for the requested organisation.

**Comment by mcginkel** [comment]
The initial spec we discussed is that all URL's for events and endpoints would be the same for a MP,LA,SIS and LMS as they are supplied as SAAS services. The school identifier is added in of the authentication token.

an argument pro:
* you get authentication for a certain scope in the context of a school. The moment you check this is the authentication token, so you do not need to test that in every request for that session again.

**Comment by Jorimvdw** [comment]
Agree with Kees. But there is one problem with the events. I think we need to add the digitaldelivery-id as a field of an event. Otherwise you don't know for which organisation you need to request a token for in order to be allowed to retrieve the data.

**Comment by mcginkel** [comment]
Not fully agree with the fact that we need to add school id to the events.
When you send an event, you need to authenticate to send the events (we dont want open systems). If you send events for sis, usage, progress and entitlements you  do that in the context of a school, so you can request a auth token for that school.
The event handler has the school identity via the token, which is safer then adding it as data.

**Comment by hhaarsma** [comment]
The only downside of this approach is that during the authentication step also an authorisation action has to be done (to validate that the partner in the eco-system that makes a call with a valid client id/secret, is also entitled to act on behalf of a certain school). 
As a result we will have to make a change in the authentication service, so that it is aware of the SEM solution/requirements and checks the given consents.
