### ISSUE TITLE
Decide which values of SchoolSubject are mandatory

### ISSUE THREAD

**Issue by mcginkel** [stichtingsem/ecosystem#46]
We have to decide which properties are mandatory, which properties combined form the primary key

![image](https://user-images.githubusercontent.com/8106362/153846703-97186769-ecb9-4b81-8d0d-e65455c33378.png)

Note: image is out of date

example
{
  "subjectCode": "0071",
  "schoolSubjectAbbr": "en",
  "schoolSubjectName": "Engels",
  "level": "vmbo-bb",
  "levelYear": 2,
  "schoolLevel": "onderbouw-2",
  "schemaVersion": 0
}

**Comment by niesink** [comment]
In the SIS API workgroup meeting we found that the introduction of an (explicit) identifier might be beneficial.

The main reason for this is that it does not seem feasible to define a 'combined' primary key based on the current fields of SchoolSubject. The two problems with combining (some of) the current fields into a primary key are:
* it is quite possible, at least in Somtoday, to create two unique SchoolSubjects for which each of the fields specified above are identical, yet they are considered two seperate SchoolSubjects connected to their own organizational units with their own settings
* at least some of these fields are not static, meaning they can be changed during the year (e.g. the abbrevation or name). Using these fields as part of the combined primary key would imply the changing of such a field should trigger delete and create events, which might have unwanted consequences, for instance on the LA or MP side.

The suggestion therefor would be to add an identifier (uuid), chosen by the SIS, to the SchoolSubject object.

**Comment by kvoer** [comment]
We discussed this issue in the technical track of 25/3 and concluded that we add **a unique identifier** for the SchoolSubject.

- Within the Ecosystem we can use this ID to communicate changes in SchoolSubjectName, SchoolSubjectAbbr, and SchoolLevel.

- Schools have the flexibility to entitle digital learning materials for a specific variant of the combination SubjectCode, Level, and LevelYear. For example Cambridge Engels vwo 6 and Engels vwo 6.

- Fields SubjectCode, Level, LevelYear are not allowed to change and require a new SchoolSubject, exception is change from empty to filled.

- Adding an ID makes deletion of SchoolSubjects in the SIS problematic. Entitlements that were bought on the SchoolSubject cannot be activated anymore. By accident deletion and replacing with a new SchoolSubject is not possible because the ID differs. This is a downside consequence for using a unique ID.
